### ISSUE TITLE
Unable to Validate Spinner

### ISSUE THREAD

**Issue by aakashsinha** [vijayrawatsan/android-json-form-wizard#15]
Hi,

I tried validating (required field) the spinner in a similar ways as we did for editText and Mobile but it is not working. Can you please help me out with this?

**Comment by vijayrawatsan** [comment]
@aakashsinha 
Currently validation is available only for edit_text and image_picker. Validation is an inprogress task. Will update the readme when validation is complete.
Thanks

**Comment by vijayrawatsan** [comment]
Now you can please check https://github.com/vijayrawatsan/android-json-form-wizard/blob/master/sample/src/main/assets/data.json
