### ISSUE TITLE
Spinner is not displaying

### ISSUE THREAD

**Issue by a-v-ebrahimi** [vijayrawatsan/android-json-form-wizard#23]
This is my form.json, but it does not display the spinner

{
    "count":"1",
    "step1":{
        "fields":[
            {
                "key":"from_account",
                "type":"spinner",
                "hint": "Select source account",
                "values":["0100719742003", "0200404805009"],
                "v_required":{  "value" : "true",
                    "err" : "Please choose a value to proceed."
                }
            }
        ],
        "title":"Step 1 of 1"
    }
}

**Comment by vijayrawatsan** [comment]
What does it display? Does it throw an error?

**Comment by a-v-ebrahimi** [comment]
I found the problem is that your gradle library is not latest, I just downloaded library and compiled it myself, now it's working!
