### ISSUE TITLE
is spinner supports in this Library

### ISSUE THREAD

**Issue by kprathap23** [vijayrawatsan/android-json-form-wizard#3]
can we create a dynamic spinner using this Library ?

**Comment by vijayrawatsan** [comment]
Hey @kprathap23 
It does not support spinner right now. But it can be supported easily. Don't have time this weekend. But will try to do in the next.

**Comment by vijayrawatsan** [comment]
Now spinner is supported after this pull request
https://github.com/vijayrawatsan/android-json-form-wizard/pull/5
