### ISSUE TITLE
ic_launcher in mipmap folders

### ISSUE THREAD

**Issue by LuigiPapino** [vijayrawatsan/android-json-form-wizard#4]
According to this: http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

I think that is necessary to delete the ic_launcher in mipmap folders.

Oh and Thanks for the awesome work!

**Comment by vijayrawatsan** [comment]
Thanks Luigi. Will work upon this during weekend.

**Comment by vijayrawatsan** [comment]
Done in https://github.com/vijayrawatsan/android-json-form-wizard/pull/6
