### ISSUE TITLE
How to add validation

### ISSUE THREAD

**Issue by AungThiha** [vijayrawatsan/android-json-form-wizard#8]
Could you please tell me how to add validation to views.
Thanks

**Comment by vijayrawatsan** [comment]
Fields validation is still pending in this library. What do you mean by view validation?

**Comment by AungThiha** [comment]
Thanks for reply :)
yes, it may called fields validation ( not sure how it's called). What I want is, for example, if the user didn't choose any photo in ImageChooser and when the next button is clicked, inform the user that he/she has to choose photo before inflating the next fragment. Another example is, in EditText for email, when the user enter invalid email ( no @ sign for instance), validate the editext field using regex. Validation features may also needed for Spinner and Checkbox.

**Comment by vijayrawatsan** [comment]
@AungThiha I will start with EditText validation in my spare time. 
@nipuns @sarajmunjal @mr-bharat-verma @rohangulati15 @gitanuj @arpitanand can you guys pick some validations?

**Comment by AungThiha** [comment]
Thanks for your kind help.

**Comment by vijayrawatsan** [comment]
@AungThiha I have added validations for edit text and image picker for now. You can use latest snapshot version 1.1.0-SNAPSHOT

I have not added readme for now.
